# Use an official OpenJDK runtime as the base image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Maven project files
COPY pom.xml .
COPY src ./src
# Build the application using Maven
RUN apt-get update && apt-get install -y maven
RUN mvn clean package -DskipTests

# Expose the port your application will run on (if it's a web application)
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "target/airline-management-system-1.0-SNAPSHOT.jar"]